### ISSUE TITLE
Create vote plugin

### ISSUE THREAD

**Issue by gbionescu** [spankybot/spanky.py#4]
Create a plugin that allows users to create polls on servers.

The plugin should:
1. Count votes based on predefined reactions.
2. Be able to count votes for a poll that was created by an older bot session. This is needed, because whenever someone adds a reaction, the bot will only receive hooks for messages that have been sent since the current bot instance has been online. 
If a poll has been started and the bot has reset 3 times during 5 days, it won't be able to see votes that have been cast after the instance that created the poll has terminated.
This means that polls should probably have to be stored somewhere through the message ID.

**Comment by AlexVasiluta** [comment]
Can't you just write an onReaction event handler that sees if the message it's being reacted to is a poll, and update it accordingly?

**Comment by gbionescu** [comment]
Yep, that's why polls should be identified by the message ID with which they were posted.
